'''
AULA ENSINANDO A USAR O BREAK NO WHILE
'''

c = 0
while True: # SO VAI PARAR QUANDO EU QUEBRAR O PROGRAMA OU FOR FALSO. QUE NESTE CASO NUNCA VAI SER.
    c += 1
    print(c)
    if c == 999: # PARAR O PROGRAMA COM UMA CONDIÇÃO E DEPOIS USAR O BREAK
        break