palavra = (input('Digite algo: '))
print(palavra)
print(f'O tipo primitivo desse valor é', type(palavra))
print(f'Só tem espaços?', palavra.isspace())
print(f'É um númerico?', palavra.isalnum())
print(f'É alfabético?', palavra.isalpha())
print(f'Está em minuscula?', palavra.islower())
print(f'Está em maiuscula?', palavra.isupper())
print(f'Está capitalizada?', palavra.istitle())